#!/bin/bash
exit

# list of packages to install
cp fs/package.use /etc/portage/package.use
cp fs/world /var/lib/portage/world
sudo ACCEPT_LICENSE="* @FREE" VIDEO_CARDS="intel amdgpu radeonsi radeon nouveau fbdev vesa" emerge --ask --update --verbose-conflicts --autounmask --autounmask-write --changed-use --deep --keep-going --with-bdeps=y --jobs=8 @world
sed -i 's/replace-wscomments=no/replace-wscomments=yes/g' /etc/dispatch-conf.conf
sudo dispatch-conf

cp fs/sway /etc/sway/config
mkdir -p ~/.config/waybar/
cp fs/wayland.config ~/.config/waybar/config
cp fs/wayland.style.css ~/.config/waybar/style.css
cp fs/portals.conf ~/.config/xdg-desktop-portal/portals.conf

sed -i 's/clock="UTC"/clock="local"/g' /etc/conf.d/hwclock
# services
rc-update add metalog default
rc-update add ntpd default
rc-update add dbus default
cp fs/udevRules /etc/udev/rules.d/automount.rules
rc-update add elogind boot

# DNS
echo "Cyberia" > /etc/hostname
echo "127.0.0.1	Cyberia" > /etc/hosts
printf "nameserver 127.0.0.1\noptions edns0" > /etc/resolv.conf
chattr +i /etc/resolv.conf
cp fs/unbound.conf /etc/unbound/unbound.conf
rc-update add unbound default
rc-update add unbound restart

#hp-setup
rc-update add cupsd default
rc-update add cups-browsed default
# http://localhost:631/

# groups
gpasswd -d root audio
echo "%wheel ALL=(ALL) ALL" > /etc/sudoers.d/sudo

# user
useradd -ou 4242 -s /bin/bash -G portage,usb,video,wheel,cdrom,wireshark,lpadmin ljosalfur
passwd ljosalfur
cp fs/.Xdefaults ~/.Xdefaults
mkdir /home/ljosalfur/screenshots
printf "\n# alias for suspend to ram\nalias slp=\"echo mem | sudo tee /sys/power/state > /dev/null\"" >> /home/ljosalfur/.bashrc
printf "\nalias wipe=\"sudo grub-reboot \\\\\"Memtest86+\\\\\" && sudo reboot\"" >> /home/ljosalfur/.bashrc
printf "\n# Ranger options\nalias ranger=\"ranger --cmd='set show_hidden true' --cmd='set vcs_aware true' --cmd='set vcs_backend_git enabled' --cmd='set preview_images_method ueberzug' --cmd='set preview_images true'\"\n" >> /home/ljosalfur/.bashrc
printf "\n# Slack\nalias slack=\"(cd /opt/slack && ./slack &)\"\n" >> /home/ljosalfur/.bashrc
#emerge --ask dev-java/openjdk
#wget -O /tmp/tos.sh https://mediaserver.thinkorswim.com/installer/InstFiles/thinkorswim_installer.sh
#sh /tmp/tos.sh
#printf "\n# ThinkOrSwim\nalias thinkorswim=\"(cd ~/thinkorswim && /usr/bin/java -jar launcher.jar -Dsun.java2d.opengl=true)\"\n" >> /home/ljosalfur/.bashrc

# config
# disable trash for Thundar (gio or gvfs trash)
chattr +i /home/ljosalfur/.local/share/Trash/files
chattr +i /home/ljosalfur/.local/share/Trash/info
# disable thumbnail cache for ranger+ueberzugpp
chattr +i /home/ljosalfur/.cache/ueberzugpp
