#!/bin/bash

# https://wiki.gentoo.org/wiki/Handbook:AMD64/Working/USE
# https://wiki.gentoo.org/wiki/Gentoo_Cheat_Sheet

# world file - contains manually installed packages
# /var/lib/portage/world

sudo emaint -a sync && sudo eix-update

# firmware updates
fwupdmgr refresh --force && fwupdmgr get-updates && fwupdmgr update

sudo ACCEPT_LICENSE="* @FREE" VIDEO_CARDS="intel amdgpu radeonsi radeon nouveau fbdev vesa" emerge --ask --update --verbose-conflicts --autounmask --autounmask-write --changed-use --deep --keep-going --with-bdeps=y --exclude="" --jobs=8 @world
sudo dispatch-conf

# fix
sudo revdep-rebuild -v portage_options='--ask'
sudo ACCEPT_LICENSE="* @FREE" perl-cleaner --all

# https://wiki.gentoo.org/wiki/Security_Handbook/Staying_up-to-date
glsa-check -t all
sudo glsa-check -f $(glsa-check -t all)

# clean
sudo emerge --ask --depclean -v
eix-test-obsolete
sudo portpeek -a
#sudo eclean --deep distfiles
#sudo eclean --deep packages
# just delete all source files
#sudo rm -rf /usr/portage/distfiles
# cleanup dangling temp files TODO: use a RAM tmpfs
#sudo rm -rf /var/tmp/portage
