#!/bin/bash
echo "I would rather not execute this as is."
exit

# https://wiki.gentoo.org/wiki/Handbook:AMD64/Working/USE
# https://wiki.gentoo.org/wiki/Gentoo_Cheat_Sheet

# https://wiki.gentoo.org/wiki/Security_Handbook/Staying_up-to-date
emaint -a sync
glsa-check -t all
glsa-check -p $(glsa-check -t all)
# glsa-check -f $(glsa-check -t all)

# update
emaint -a sync
ACCEPT_LICENSE="" emerge --ask --update --verbose-conflicts --autounmask-write --changed-use --deep --keep-going --with-bdeps=y @world
# I think I had tons of conflicts with autounmask-write last time...
# dont forget to merge /etc also dont forget that it will overwrite your config instead of actually automerging...

# fix
revdep-rebuild -v portage_options='--ask'
perl-cleaner --all

# clean
emerge --ask --depclean -v
portpeek -a #-f

exit
############################################

# check enabled USE flags
portageq envvar USE | xargs -n 1

# check users of a USE flag
euse -I <flag>
quse <flag>
eix --installed-with-use <flag>

# list all files owned by a package
qlist <package-name>

# show parents of the package
equery d <package-name>

# manually step through the emerge process, lets you patch the source before compile
ebuild /usr/portage/<.ebuild> fetch
ebuild /usr/portage/<.ebuild> unpack
ebuild /usr/portage/<.ebuild> compile
ebuild /usr/portage/<.ebuild> install
ebuild /usr/portage/<.ebuild> qmerge
ebuild /usr/portage/<.ebuild> clean

# uninstall
emerge --ask --depclean -v <package>
