#!/bin/bash
echo "I would rather not execute this as is."
exit

# https://wiki.gentoo.org/wiki/Handbook:AMD64/Working/USE
# https://wiki.gentoo.org/wiki/Gentoo_Cheat_Sheet

# https://wiki.gentoo.org/wiki/Security_Handbook/Staying_up-to-date
sudo emaint -a sync
#sudo glsa-check -p $(glsa-check -t all)
#sudo glsa-check -f $(glsa-check -t all)
#unfirejail bzip2 by deleting symlink
# /usr/local/bin/patch too
sudo PATH=$(echo $PATH | sed 's/\/usr\/local\/bin//g') ACCEPT_LICENSE="*" emerge --ask --update --verbose-conflicts --autounmask-write --changed-use --deep --keep-going --with-bdeps=y --exclude="" @world
# I think I had tons of conflicts with autounmask-write last time...
# dont forget to merge /etc also dont forget that it will overwrite your config instead of actually automerging...

# fix
sudo revdep-rebuild -v portage_options='--ask'
sudo ACCEPT_LICENSE="*" perl-cleaner --all

# clean
sudo emerge --ask --depclean -v
sudo portpeek -a #-f

############################################
exit

# world file - contains manually installed packages
# /var/lib/portage/world

# check enabled USE flags
portageq envvar USE | xargs -n 1

# check users of a USE flag
euse -I <flag>
quse <flag>
eix --installed-with-use <flag>

# show merge history
qlop -m  -v

# merge specific version
emerge ~<package-name>-version

# list all files owned by a package
qlist <package-name>

# show parents of the package
equery d <package-name>

# manually step through the emerge process, lets you patch the source before compile
ebuild /usr/portage/<.ebuild> fetch
ebuild /usr/portage/<.ebuild> unpack
ebuild /usr/portage/<.ebuild> compile
ebuild /usr/portage/<.ebuild> install
ebuild /usr/portage/<.ebuild> qmerge
ebuild /usr/portage/<.ebuild> clean

# uninstall
emerge --ask --depclean -v <package>
