#!/bin/bash
echo "I would rather not execute this as is."
exit

# https://wiki.gentoo.org/wiki/Handbook:AMD64/Working/USE
# https://wiki.gentoo.org/wiki/Gentoo_Cheat_Sheet

# https://wiki.gentoo.org/wiki/Security_Handbook/Staying_up-to-date
sudo emaint -a sync && sudo eix-update
#sudo glsa-check -p $(glsa-check -t all)
#sudo glsa-check -f $(glsa-check -t all)

# kernel upgrade
eselect kernel list
sudo eselect kernel set 1
curl -L https://github.com/feniksa/gentoo_ACS_override_patch/archive/master.zip -o /tmp/master.zip
unzip /tmp/master.zip
sudo cp -r /tmp/gentoo_ACS_override_patch-master/sys-kernel /etc/portage/patches/sys-kernel
# this patch is only activated after gentoo-sources emerge
sudo emerge -v gentoo-sources
zcat /proc/config.gz > /tmp/current_kernel.config
sudo genkernel --kernel-config=/tmp/current_kernel.config all
sudo grub-mkconfig -o /boot/grub/grub.cfg
sudo eclean-kernel --ask -n 2 # keep the new and old kernel, warning: doesn't actually care about version numbers

### Firejail breaks some things with an ld.so/libsandbox.so error and something about env vars being too long
# https://bugs.gentoo.org/694966
# unfirejail bzip2 by deleting symlinks at /usr/local/bin/
# bzip2, patch, fontforge not working

sudo ACCEPT_LICENSE="*" emerge --ask --update --verbose-conflicts --autounmask-write --changed-use --deep --keep-going --with-bdeps=y --exclude="" @world
# I think I had tons of conflicts with autounmask-write last time...
# dont forget to merge /etc also dont forget that it will overwrite your config instead of actually automerging...
# use dispatch-conf instead of etc-update
sudo dispatch-conf

# fix
sudo revdep-rebuild -v portage_options='--ask'
sudo ACCEPT_LICENSE="*" perl-cleaner --all

# clean
sudo emerge --ask --depclean -v
eix-test-obsolete
sudo portpeek -a
sudo eclean --deep distfiles
sudo eclean --deep packages
# just delete all source files
sudo rm -rf /usr/portage/distfiles
# cleanup dangling temp files TODO: use a RAM tmpfs
sudo rm -rf /var/tmp/portage

############################################
exit

# world file - contains manually installed packages
# /var/lib/portage/world

# check enabled USE flags
portageq envvar USE | xargs -n 1

# check users of a USE flag
euse -I <flag>
quse <flag>
eix --installed-with-use <flag>

# show merge history
qlop -m  -v

# merge specific version
emerge ~<package-name>-version

# list all files owned by a package
qlist <package-name>

# show parents of the package
equery d <package-name>

# manually step through the emerge process, lets you patch the source before compile
ebuild /usr/portage/<.ebuild> fetch
ebuild /usr/portage/<.ebuild> unpack
ebuild /usr/portage/<.ebuild> compile
ebuild /usr/portage/<.ebuild> install
ebuild /usr/portage/<.ebuild> qmerge
ebuild /usr/portage/<.ebuild> clean

# uninstall
emerge --ask --depclean -v <package>
