#!/bin/sh
#gnore everything that is not sd-
KERNEL!="sd[a-z]*", GOTO="exit"
ACTION=="add", PROGRAM!="/sbin/blkid %N", GOTO="exit"

# import some useful filesystem info as variables
IMPORT{program}="/sbin/blkid -o udev -p %N"

# get the label if present, otherwise assign one based on device/partition
ENV{ID_FS_LABEL}!="", ENV{dir_name}="%E{ID_FS_LABEL}"
ENV{ID_FS_LABEL}=="", ENV{dir_name}="%k"

# create the dir in /media and symlink it to /mnt
ACTION=="add", RUN+="/bin/mkdir -p '/media/%E{dir_name}'"

### VFAT/NTFS
ACTION=="add", ENV{ID_FS_TYPE}=="vfat|ntfs", RUN+="/bin/mount -t auto -o gid=100,dmask=000,fmask=111,utf8,flush,rw,noatime,users /dev/%k '/media/%E{dir_name}'"
ACTION=="add", ENV{ID_FS_TYPE}!="vfat|ntfs", RUN+="/bin/mount -t auto -o noatime /dev/%k '/media/%E{dir_name}'"

# clean up after device removal
ACTION=="remove", ENV{dir_name}!="", RUN+="/bin/umount -l '/media/%E{dir_name}'", RUN+="/bin/rmdir '/media/%E{dir_name}'"

# exit
LABEL="exit"
