server:
	interface: 127.0.0.1
	access-control: 127.0.0.0/8 allow
	tls-cert-bundle: "/etc/ssl/certs/ca-certificates.crt"

forward-zone:
	# Tailscale
	name: "*.ts.net."
	forward-addr: 100.100.100.100

forward-zone:
	name: "."
	forward-tls-upstream: yes
	# Cloudflare
	forward-addr: 1.1.1.1@853#cloudflare-dns.com
	forward-addr: 1.0.0.1@853#cloudflare-dns.com
	# Quad9
	forward-addr: 9.9.9.9@853#dns.quad9.net
	forward-addr: 149.112.112.112@853#dns.quad9.net
